### PR TITLE
docs: added points field to the subscriptions

### PR DESCRIPTION
**Pull request by ginnun**
Added some details to subscription docs on:

- Providing points
- Topics array removed, now API accepts one topic at a time

### CODE REVIEW

**Review by rhyslbw — COMMENTED** [review]
This is a good example of where Conventional Commits can help with a review @ginnun. If you separate the formatting changes to adhere to a character line limit, from the actual meaningful changes, the reviewer can filter out the noise. As an exercise try reworking this as 3 commits:

1. `docs: wrap long lines`
2. `docs: correct contributor name`
3. `docs: add points field to the subscriptions`

**Review by rhyslbw — CHANGES_REQUESTED** [review]
This is a good example of where Conventional Commits can help with a review @ginnun. If you separate the formatting changes to adhere to a character line limit, from the actual meaningful changes, the reviewer can filter out the noise. As an exercise try reworking this as 3 commits:

1. `docs: wrap long lines`
2. `docs: correct contributor name`
3. `docs: add points field to the subscriptions`

**Comment by ginnun** [comment]
My bad, thanks for the reminder @rhyslbw .

**Comment by ginnun** [comment]
This PR is now active here: https://github.com/will-break-it/wallet-architecture/pull/7 
@rhyslbw @will-break-it

**Pull request closed without merging**
